using System.Collections.Immutable;
using TmEngine.Domain.Models;

namespace TmEngine.Domain.Cards;

/// <summary>
/// All card definitions hardcoded in the engine. Replaces the JSON-based CardDataLoader.
/// </summary>
public static class CardDefinitions
{
    public static ImmutableDictionary<string, CardDefinition> LoadAll()
    {
        var cards = new CardDefinition[]
        {
        D("001", "Colonizer Training Camp", CardType.Automated, 8, [Tag.Building, Tag.Jovian], Expansion.Base, [new CardRequirement("max_oxygen", 5)], new FixedVictoryPoints(2), "Oxygen must be 5% or less"),
        D("002", "Asteroid Mining Consortium", CardType.Automated, 13, [Tag.Jovian], Expansion.CorporateEra, [new CardRequirement("titanium_production", 1)], new FixedVictoryPoints(1), "Requires that you have titanium production. Decrease any titanium production 1 step and increase your own 1 step"),
        D("003", "Deep Well Heating", CardType.Automated, 13, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Increase your Energy production 1 step. Increase temperature 1 step"),
        D("004", "Cloud Seeding", CardType.Automated, 11, [], Expansion.Base, [new CardRequirement("oceans", 3)], null, "Requires 3 ocean tiles. Decrease your MC production 1 step and any heat production 1 step. Increase your Plant production 2 steps"),
        D("005", "Search for Life", CardType.Active, 3, [Tag.Science], Expansion.Base, [new CardRequirement("max_oxygen", 6)], new PerResourceVictoryPoints(3, 1, "005"), "Action: Spend 1 MC to reveal the top card of the draw deck. If that card has a Microbe tag, add a Science resource here. 3 VPs if you have one or more Science resources here"),
        D("006", "Inventors' Guild", CardType.Active, 9, [Tag.Science], Expansion.CorporateEra, [], null, ""),
        D("007", "Martian Rails", CardType.Active, 13, [Tag.Building], Expansion.Base, [], null, "Action: Spend 1 Energy to gain 1 MC for each City tile ON MARS"),
        D("008", "Capital", CardType.Automated, 26, [Tag.Building, Tag.City], Expansion.Base, [new CardRequirement("oceans", 4)], new PerResourceVictoryPoints(1, 1, "008"), "(Requires 4 ocean tiles. Place this tile. Decrease your Energy production 2 steps and increase your MC production 5 steps. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE"),
        D("009", "Asteroid", CardType.Event, 14, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise temperature 1 step and gain 2 titanium. Remove up to 3 Plants from any player"),
        D("010", "Comet", CardType.Event, 21, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise temperature 1 step and place an ocean tile. Remove up to 3 Plants from any player"),
        D("011", "Big Asteroid", CardType.Event, 27, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise temperature 2 steps and gain 4 titanium. Remove up to 4 Plants from any player"),
        D("012", "Water Import from Europa", CardType.Active, 25, [Tag.Space, Tag.Jovian], Expansion.Base, [], new PerResourceVictoryPoints(1, 1, "012"), "Action: Pay 12 MC to place an ocean tile. TITANIUM MAY BE USED as if playing a Space card. 1 VP for each Jovian tag you have"),
        D("013", "Space Elevator", CardType.Active, 27, [Tag.Building, Tag.Space], Expansion.CorporateEra, [], new FixedVictoryPoints(2), "Action: Spend 1 steel to gain 5 MC. Increase your titanium production 1 step"),
        D("014", "Development Center", CardType.Active, 11, [Tag.Building, Tag.Science], Expansion.CorporateEra, [], null, "Action: Spend 1 Energy to draw a card"),
        D("015", "Equatorial Magnetizer", CardType.Active, 11, [Tag.Building], Expansion.Base, [], null, "Action: Decrease your Energy production 1 step to increase your terraform rating 1 step"),
        D("016", "Domed Crater", CardType.Automated, 24, [Tag.Building, Tag.City], Expansion.Base, [new CardRequirement("max_oxygen", 7)], new FixedVictoryPoints(1), "Oxygen must be 7% or less. Gain 3 plants. Place a City tile. Decrease your Energy production 1 step and increase your MC production 3 steps"),
        D("017", "Noctis City", CardType.Automated, 18, [Tag.Building, Tag.City], Expansion.Base, [], null, "Decrease your Energy production 1 step and increase your MC production 3 steps. Place a city ON THE RESERVED AREA, disregarding normal placement restrictions"),
        D("018", "Methane from Titan", CardType.Automated, 28, [Tag.Space, Tag.Jovian], Expansion.Base, [new CardRequirement("oxygen", 2)], new FixedVictoryPoints(2), "Requires 2% oxygen. Increase your heat production 2 steps and your Plant production 2 steps"),
        D("019", "Imported Hydrogen", CardType.Event, 16, [Tag.Event, Tag.Space, Tag.Earth], Expansion.Base, [], null, "Gain 3 Plants, or add 3 Microbes or 2 Animals to ANOTHER card. Place an ocean tile"),
        D("020", "Research Outpost", CardType.Active, 18, [Tag.Building, Tag.City, Tag.Science], Expansion.Base, [], null, "Effect: When you play a card, you pay 1 MC less for it. Place a city tile NEXT TO NO OTHER TILE"),
        D("021", "Phobos Space Haven", CardType.Automated, 25, [Tag.Space, Tag.City], Expansion.Base, [], new FixedVictoryPoints(3), "Increase your titanium production 1 step and place a City tile ON THE RESERVED AREA"),
        D("022", "Black Polar Dust", CardType.Automated, 15, [], Expansion.Base, [], null, "Place an ocean tile. Decrease your MC production 2 steps and increase your heat production 3 steps"),
        D("023", "Arctic Algae", CardType.Active, 12, [Tag.Plant], Expansion.Base, [new CardRequirement("max_temperature", -12)], null, "Effect: When anyone places an ocean tile, gain 2 Plants. It must be -12 C or colder to play. Gain 1 Plant"),
        D("024", "Predators", CardType.Active, 14, [Tag.Animal], Expansion.Base, [new CardRequirement("oxygen", 11)], new PerResourceVictoryPoints(1, 1, "024"), "Action: Remove 1 Animal from any card and add it to this card. Requires 11% oxygen. 1 VP per Animal on this card"),
        D("025", "Space Station", CardType.Active, 10, [Tag.Space], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Effect: When you play a Space card, you pay 2 MC less for it"),
        D("026", "Eos Chasma National Park", CardType.Automated, 16, [Tag.Building, Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -12)], new FixedVictoryPoints(1), "Requires -12 C or warmer. Add 1 Animal TO ANY ANIMAL CARD. Gain 3 Plants. Increase your MC production 2 steps"),
        D("027", "Interstellar Colony Ship", CardType.Event, 24, [Tag.Event, Tag.Space, Tag.Earth], Expansion.CorporateEra, [new CardRequirement("science_tag", 5)], new FixedVictoryPoints(4), ""),
        D("028", "Security Fleet", CardType.Active, 12, [Tag.Space], Expansion.CorporateEra, [], new PerResourceVictoryPoints(1, 1, "028"), "Action: Spend 1 titanium to add 1 fighter resource to this card. 1 VP for each fighter resource on this card"),
        D("029", "Cupola City", CardType.Automated, 16, [Tag.Building, Tag.City], Expansion.Base, [new CardRequirement("max_oxygen", 9)], null, "Oxygen must be 9% or less. Place a City tile. Decrease your Energy production 1 step and increase your MC production 3 steps"),
        D("030", "Lunar Beam", CardType.Automated, 13, [Tag.Power, Tag.Earth], Expansion.Base, [], null, "Decrease your MC production 2 steps and increase your heat production and Energy production 2 steps each"),
        D("031", "Optimal Aerobraking", CardType.Active, 7, [Tag.Space], Expansion.Base, [], null, "Effect: When you play a Space Event, you gain 3 MC and 3 heat"),
        D("032", "Underground city", CardType.Automated, 18, [Tag.Building, Tag.City], Expansion.Base, [], null, "Place a City tile. Decrease your Energy production 2 steps and increase your steel production 2 steps"),
        D("033", "Regolith Eaters", CardType.Active, 13, [Tag.Microbe, Tag.Science], Expansion.Base, [], null, "Action: Add 1 Microbe to this card, or remove 2 Microbes from this card to raise oxygen level 1 step"),
        D("034", "GHG Producing Bacteria", CardType.Active, 8, [Tag.Microbe, Tag.Science], Expansion.Base, [new CardRequirement("oxygen", 4)], null, "Action: Add 1 Microbe to this card, or remove 2 Microbes to raise temperature 1 step. Requires 4% oxygen"),
        D("035", "Ants", CardType.Active, 9, [Tag.Microbe], Expansion.Base, [new CardRequirement("oxygen", 4)], new PerResourceVictoryPoints(1, 2, "035"), "Action: Remove 1 Microbe from any card to add 1 to this card. Requires 4% oxygen. 1 VP per 2 Microbes on this card"),
        D("036", "Release of Inert Gases", CardType.Event, 14, [Tag.Event], Expansion.Base, [], null, "Raise your terraform rating 2 steps"),
        D("037", "Nitrogen-Rich Asteroid", CardType.Event, 31, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise your terraforming rating 2 steps and temperature 1 step. Increase your Plant production 1 step, or 4 steps if you have 3 Plant tags"),
        D("038", "Rover Construction", CardType.Active, 8, [Tag.Building], Expansion.Base, [], new FixedVictoryPoints(1), "Effect: When any City tile is placed, gain 2 MC"),
        D("039", "Deimos Down", CardType.Event, 31, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise temperature 3 steps and gain 4 steel. Remove up to 8 Plants from any player"),
        D("040", "Asteroid Mining", CardType.Automated, 30, [Tag.Space, Tag.Jovian], Expansion.Base, [], new FixedVictoryPoints(2), "Increase your titanium production 2 steps"),
        D("041", "Food Factory", CardType.Automated, 12, [Tag.Building], Expansion.Base, [], new FixedVictoryPoints(1), "Decrease your Plant production 1 step and increase your MC production 4 steps"),
        D("042", "Archaebacteria", CardType.Automated, 6, [Tag.Microbe], Expansion.Base, [new CardRequirement("max_temperature", -18)], null, "It must be -18 C or colder. Increase your Plant production 1 step"),
        D("043", "Carbonate Processing", CardType.Automated, 6, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 1 step and increase your heat production 3 steps"),
        D("044", "Natural Preserve", CardType.Automated, 9, [Tag.Building, Tag.Science], Expansion.Base, [new CardRequirement("max_oxygen", 4)], new FixedVictoryPoints(1), "Oxygen must be 4% or less. Place this tile NEXT TO NO OTHER TILE. Increase your MC production 1 step"),
        D("045", "Nuclear Power", CardType.Automated, 10, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Decrease your MC production 2 steps and increase your Energy production 3 steps"),
        D("046", "Lightning Harvest", CardType.Automated, 8, [Tag.Power], Expansion.CorporateEra, [new CardRequirement("science_tag", 3)], new FixedVictoryPoints(1), "Requires 3 Science tags. Increase your Energy production and your MC production up one step each"),
        D("047", "Algae", CardType.Automated, 10, [Tag.Plant], Expansion.Base, [new CardRequirement("oceans", 5)], null, "Requires 5 ocean tiles. Gain 1 Plant and increase your Plant production 2 steps"),
        D("048", "Adapted Lichen", CardType.Automated, 9, [Tag.Plant], Expansion.Base, [], null, "Increase your Plant production 1 step"),
        D("049", "Tardigrades", CardType.Active, 4, [Tag.Microbe], Expansion.CorporateEra, [], new PerResourceVictoryPoints(1, 4, "049"), "Action: Add 1 Microbe to this card. 1 VP per 4 Microbes on this card"),
        D("050", "Virus", CardType.Event, 1, [Tag.Event, Tag.Microbe], Expansion.CorporateEra, [], null, "Remove up to 2 Animals or 5 Plants from any player"),
        D("051", "Miranda Resort", CardType.Automated, 12, [Tag.Space, Tag.Jovian], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Increase your MC production 1 step for each Earth tag you have"),
        D("052", "Fish", CardType.Active, 9, [Tag.Animal], Expansion.Base, [new CardRequirement("temperature", 2)], new PerResourceVictoryPoints(1, 1, "052"), "Action: Add 1 Animal to this card. Requires +2 C or warmer. Decrease any Plant production 1 step. 1 VP for each Animal on this card"),
        D("053", "Lake Marineris", CardType.Automated, 18, [], Expansion.Base, [new CardRequirement("temperature", 0)], new FixedVictoryPoints(2), "Requires 0 C or warmer. Place 2 ocean tiles"),
        D("054", "Small Animals", CardType.Active, 6, [Tag.Animal], Expansion.Base, [new CardRequirement("oxygen", 6)], new PerResourceVictoryPoints(1, 2, "054"), "Action: Add 1 Animal to this card. Requires 6% oxygen. Decrease any Plant production 1 step. 1 VP per 2 Animals on this card"),
        D("055", "Kelp Farming", CardType.Automated, 17, [Tag.Plant], Expansion.Base, [new CardRequirement("oceans", 6)], new FixedVictoryPoints(1), "Requires 6 ocean tiles. Increase your MC production 2 steps and your Plant production 3 steps. Gain 2 Plants"),
        D("056", "Mine", CardType.Automated, 4, [Tag.Building], Expansion.CorporateEra, [], null, "Increase your steel production 1 step"),
        D("057", "Vesta Shipyard", CardType.Automated, 15, [Tag.Space, Tag.Jovian], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Increase your titanium production 1 step"),
        D("058", "Beam from a Thorium Asteroid", CardType.Automated, 32, [Tag.Power, Tag.Space, Tag.Jovian], Expansion.Base, [new CardRequirement("jovian_tag", 1)], new FixedVictoryPoints(1), "Requires a Jovian tag. Increase your heat production and Energy production 3 steps each"),
        D("059", "Mangrove", CardType.Automated, 12, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", 4)], new FixedVictoryPoints(1), "Requires +4 C or warmer. Place a greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this"),
        D("060", "Trees", CardType.Automated, 13, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -4)], new FixedVictoryPoints(1), "Requires -4 C or warmer. Increase your Plant production 3 steps. Gain 1 Plant"),
        D("061", "Great Escarpment Consortium", CardType.Automated, 6, [], Expansion.CorporateEra, [new CardRequirement("steel_production", 1)], null, "Requires that you have steel production. Decrease any steel production 1 step and increase your own 1 step"),
        D("062", "Mineral Deposit", CardType.Event, 5, [Tag.Event], Expansion.CorporateEra, [], null, "Gain 5 steel"),
        D("063", "Mining Expedition", CardType.Event, 12, [Tag.Event], Expansion.Base, [], null, "Raise oxygen 1 step. Remove 2 plants from any player. Gain 2 steel"),
        D("064", "Mining Area", CardType.Automated, 4, [Tag.Building], Expansion.CorporateEra, [], null, "Place this tile on an area with a steel or titanium placement bonus, adjacent to another of your tiles. Increase your production of that resource 1 step"),
        D("065", "Building Industries", CardType.Automated, 6, [Tag.Building], Expansion.CorporateEra, [], null, "Decrease your Energy production 1 step and increase your steel production 2 steps"),
        D("066", "Land Claim", CardType.Event, 1, [Tag.Event], Expansion.CorporateEra, [], null, ""),
        D("067", "Mining Rights", CardType.Automated, 9, [Tag.Building], Expansion.Base, [], null, "Place this tile on an area with a steel or titanium placement bonus. Increase that production 1 step"),
        D("068", "Sponsors", CardType.Automated, 6, [Tag.Earth], Expansion.CorporateEra, [], null, "Increase your MC production 2 steps"),
        D("069", "Electro Catapult", CardType.Active, 17, [Tag.Building], Expansion.CorporateEra, [new CardRequirement("max_oxygen", 8)], new FixedVictoryPoints(1), "Action: Spend 1 plant or 1 steel to gain 7MC. Oxygen must be 8% or less. Decrease your energy production 1 step"),
        D("070", "Earth Catapult", CardType.Active, 23, [Tag.Earth], Expansion.CorporateEra, [], new FixedVictoryPoints(2), "Effect: When you play a card, you pay 2 MC less for it"),
        D("071", "Advanced Alloys", CardType.Active, 9, [Tag.Science], Expansion.CorporateEra, [], null, "Effect: Each titanium you have is worth 1 MC extra. Each steel you have is worth 1 MC extra"),
        D("072", "Birds", CardType.Active, 10, [Tag.Animal], Expansion.Base, [new CardRequirement("oxygen", 13)], new PerResourceVictoryPoints(1, 1, "072"), "Action: Add an animal to this card. Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP per Animal on this card"),
        D("073", "Mars University", CardType.Active, 8, [Tag.Building, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Effect: When you play a Science tag, including this, you may discard a card from hand to draw a card"),
        D("074", "Viral Enhancers", CardType.Active, 9, [Tag.Microbe, Tag.Science], Expansion.CorporateEra, [], null, "Effect: When you play a plant, microbe, or an animal tag, including this, gain 1 plant or add 1 resource to THAT CARD"),
        D("075", "Towing a Comet", CardType.Event, 23, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Gain 2 plants. Raise oxygen level 1 step and place an ocean tile"),
        D("076", "Space Mirrors", CardType.Active, 3, [Tag.Space, Tag.Power], Expansion.Base, [], null, "Action: Spend 7 MC to increase your energy production 1 step"),
        D("077", "Solar Wind Power", CardType.Automated, 11, [Tag.Power, Tag.Space, Tag.Science], Expansion.Base, [], null, "Increase your energy production 1 step and gain 2 titanium"),
        D("078", "Ice Asteroid", CardType.Event, 23, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Place 2 ocean tiles"),
        D("079", "Quantum Extractor", CardType.Active, 13, [Tag.Power, Tag.Science], Expansion.CorporateEra, [new CardRequirement("science_tag", 4)], null, "Effect: When you play a Space card, you pay 2 MC less for it. Requires 4 science tags. Increase your energy production 4 steps"),
        D("080", "Giant Ice Asteroid", CardType.Event, 36, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Raise temperature 2 steps and place 2 ocean tiles. Remove up to 6 plants from any player"),
        D("081", "Ganymede Colony", CardType.Automated, 20, [Tag.City, Tag.Space, Tag.Jovian], Expansion.Base, [], new PerResourceVictoryPoints(1, 1, "081"), "Place a city tile ON THE RESERVED AREA. 1 VP per Jovian tag you have"),
        D("082", "Callisto Penal Mines", CardType.Automated, 24, [Tag.Space, Tag.Jovian], Expansion.CorporateEra, [], new FixedVictoryPoints(2), "Increase your MC production 3 steps"),
        D("083", "Giant Space Mirror", CardType.Automated, 17, [Tag.Space, Tag.Power], Expansion.Base, [], null, "Increase your energy production 3 steps"),
        D("084", "Trans-Neptune Probe", CardType.Automated, 6, [Tag.Space, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), ""),
        D("085", "Commercial District", CardType.Automated, 16, [Tag.Building], Expansion.CorporateEra, [], new PerResourceVictoryPoints(1, 1, "085"), "Decrease your energy production 1 step and increase your MC production 4 steps. Place this tile. 1 VP PER ADJACENT CITY TILE"),
        D("086", "Robotic Workforce", CardType.Automated, 9, [Tag.Science], Expansion.CorporateEra, [], null, "Duplicate only the production box of one of your building cards"),
        D("087", "Grass", CardType.Automated, 11, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -16)], null, "Requires -16 C or warmer. Increase your plant production 1 step. Gain 3 plants"),
        D("088", "Heather", CardType.Automated, 6, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -14)], null, "Requires -14 C or warmer. Increase your plant production 1 step. Gain 1 plant"),
        D("089", "Peroxide Power", CardType.Automated, 7, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Decrease your MC production 1 step and increase your Energy production 2 steps"),
        D("090", "Research", CardType.Automated, 11, [Tag.Science, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Counts as playing 2 science cards. Draw 2 cards"),
        D("091", "Gene Repair", CardType.Automated, 12, [Tag.Science], Expansion.CorporateEra, [new CardRequirement("science_tag", 3)], new FixedVictoryPoints(2), "Requires 3 science tags. Increase your MC production 2 steps"),
        D("092", "Io Mining Industries", CardType.Automated, 41, [Tag.Space, Tag.Jovian], Expansion.CorporateEra, [], new PerResourceVictoryPoints(1, 1, "092"), "Increase your titanium production 2 steps and your MC production 2 steps. 1 VP per Jovian tag you have"),
        D("093", "Bushes", CardType.Automated, 10, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -10)], null, "Requires -10 C or warmer. Increase your plant production 2 steps. Gain 2 plants"),
        D("094", "Mass Converter", CardType.Active, 8, [Tag.Power, Tag.Science], Expansion.CorporateEra, [new CardRequirement("science_tag", 5)], null, "Effect: When you play a Space card, you pay 2 MC less for it. Requires 5 science tags. Increase your energy production 6 steps"),
        D("095", "Physics Complex", CardType.Active, 12, [Tag.Building, Tag.Science], Expansion.CorporateEra, [], new PerResourceVictoryPoints(2, 1, "095"), "Action: Spend 6 Energy to add a science resource to this card. 2 VP for each science resource on this card"),
        D("096", "Greenhouses", CardType.Automated, 6, [Tag.Building, Tag.Plant], Expansion.Base, [], null, "Gain 1 plant for each city tile in play"),
        D("097", "Nuclear Zone", CardType.Automated, 10, [Tag.Earth], Expansion.Base, [], new FixedVictoryPoints(-2), "Place this tile and raise temperature 2 steps"),
        D("098", "Tropical Resort", CardType.Automated, 13, [Tag.Building], Expansion.CorporateEra, [], new FixedVictoryPoints(2), "Reduce your heat production 2 steps and increase your MC production 3 steps"),
        D("099", "Toll Station", CardType.Automated, 12, [Tag.Space], Expansion.CorporateEra, [], null, "Increase your MC production 1 step for each space tag your OPPONENTS have"),
        D("100", "Fueled Generators", CardType.Automated, 1, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Decrease your MC production 1 step and increase your Energy production 1 step"),
        D("101", "Ironworks", CardType.Active, 11, [Tag.Building], Expansion.Base, [], null, "Action: Spend 4 energy to gain 1 steel and raise oxygen 1 step"),
        D("102", "Power Grid", CardType.Automated, 18, [Tag.Power], Expansion.Base, [], null, "Increase your Energy production step for each Power tag you have, including this"),
        D("103", "Steelworks", CardType.Active, 15, [Tag.Building], Expansion.Base, [], null, "Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step"),
        D("104", "Ore Processor", CardType.Active, 13, [Tag.Building], Expansion.Base, [], null, "Action: Spend 4 energy to gain 1 titanium and increase oxygen 1 step"),
        D("105", "Earth Office", CardType.Active, 1, [Tag.Earth], Expansion.CorporateEra, [], null, "Effect: When you play an Earth card, you pay 3 MC less for it"),
        D("106", "Acquired Company", CardType.Automated, 10, [Tag.Earth], Expansion.CorporateEra, [], null, "Increase your MC production 3 steps"),
        D("107", "Media Archives", CardType.Automated, 8, [Tag.Earth], Expansion.CorporateEra, [], null, "Gain 1 MC for each event EVER PLAYED by all players"),
        D("108", "Open City", CardType.Automated, 23, [Tag.Building, Tag.City], Expansion.Base, [new CardRequirement("oxygen", 12)], new FixedVictoryPoints(1), "Requires 12% oxygen. Gain 2 plants. Place a City tile. Decrease your Energy production 1 step and increase your MC production 4 steps"),
        D("109", "Media Group", CardType.Active, 6, [Tag.Earth], Expansion.CorporateEra, [], null, "Effect: After you play an event card, you gain 3MC"),
        D("110", "Business Network", CardType.Active, 4, [Tag.Earth], Expansion.CorporateEra, [], null, "Decrease your MC production 1 step"),
        D("111", "Business Contacts", CardType.Event, 7, [Tag.Event, Tag.Earth], Expansion.CorporateEra, [], null, ""),
        D("112", "Bribed Committee", CardType.Event, 7, [Tag.Event, Tag.Earth], Expansion.CorporateEra, [], new FixedVictoryPoints(-2), "Raise your TR 2 steps"),
        D("113", "Solar Power", CardType.Automated, 11, [Tag.Building, Tag.Power], Expansion.Base, [], new FixedVictoryPoints(1), "Increase your energy production 1 step"),
        D("114", "Breathing Filters", CardType.Automated, 11, [Tag.Science], Expansion.Base, [new CardRequirement("oxygen", 7)], new FixedVictoryPoints(2), "Requires 7% oxygen"),
        D("115", "Artificial Photosynthesis", CardType.Automated, 12, [Tag.Science], Expansion.Base, [], null, "Increase your plant production 1 step or your energy production 2 steps"),
        D("116", "Artificial Lake", CardType.Automated, 15, [Tag.Building], Expansion.Base, [new CardRequirement("temperature", -6)], new FixedVictoryPoints(1), "Requires -6 C or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN"),
        D("117", "Geothermal Power", CardType.Automated, 11, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Increase your energy production 2 step"),
        D("118", "Farming", CardType.Automated, 16, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", 4)], new FixedVictoryPoints(2), "Requires +4 C or warmer. Increase your MC production 2 steps and your plant production 2 steps. Gain 2 Plants"),
        D("119", "Dust Seals", CardType.Automated, 2, [], Expansion.Base, [new CardRequirement("max_oceans", 3)], new FixedVictoryPoints(1), "Requires 3 or less ocean tiles"),
        D("120", "Urbanized Area", CardType.Automated, 10, [Tag.Building, Tag.City], Expansion.Base, [], null, "Decrease your energy production 1 step and increase your MC production 2 steps. Place a city tile ADJACENT TO AT LEAST 2 OTHER CITY TILES"),
        D("121", "Sabotage", CardType.Event, 1, [Tag.Event], Expansion.CorporateEra, [], null, "Remove up to 3 titanium from any player, or 4 steel, or 7 MC"),
        D("122", "Moss", CardType.Automated, 4, [Tag.Plant], Expansion.Base, [new CardRequirement("oceans", 3)], null, "Requires 3 oean tiles and that you lose 1 plant. Increase your plant production 1 step"),
        D("123", "Industrial Center", CardType.Active, 4, [Tag.Building], Expansion.CorporateEra, [], null, "Action: Spend 7 MC to increase your steel production 1 step. Place this tile adjacent to a city tile"),
        D("124", "Hired Raiders", CardType.Event, 1, [Tag.Event], Expansion.CorporateEra, [], null, "Steal up to 2 steel, or 3 MC from any player"),
        D("125", "Hackers", CardType.Automated, 3, [], Expansion.CorporateEra, [], new FixedVictoryPoints(-1), "(Decrease your energy production 1 step and any MC production 2 steps. increase your MC production 2 steps"),
        D("126", "GHG Factories", CardType.Automated, 11, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 1 step and increase your heat production 4 steps"),
        D("127", "Subterranean Reservoir", CardType.Event, 11, [Tag.Event], Expansion.Base, [], null, "Place 1 ocean tile"),
        D("128", "Ecological Zone", CardType.Active, 12, [Tag.Plant, Tag.Animal], Expansion.Base, [new CardRequirement("greeneries", 1)], new PerResourceVictoryPoints(1, 2, "128"), "Effect: When you play an animal or plant tag (including these, add an animal to this card.) Requires that you have a greenery tile. Place this tile adjacent to any greenery tile. 1 VP per 2 Animals on this card"),
        D("129", "Zeppelins", CardType.Automated, 13, [], Expansion.Base, [new CardRequirement("oxygen", 5)], new FixedVictoryPoints(1), "Requires 5% oxygen. Increase your MC production 1 step for each City tile ON MARS"),
        D("130", "Worms", CardType.Automated, 8, [Tag.Microbe], Expansion.Base, [new CardRequirement("oxygen", 4)], null, "Requires 4% oxygen. Increase your Plant production 1 step for every 2 Microbe tags you have, including this"),
        D("131", "Decomposers", CardType.Active, 5, [Tag.Microbe], Expansion.Base, [new CardRequirement("oxygen", 3)], new PerResourceVictoryPoints(1, 3, "131"), "Effect: When you play an Animal, Plant, or Microbe tag, including this, add a Microbe to this card. Requires 3% oxygen. 1 VP per 3 Microbes on this card"),
        D("132", "Fusion Power", CardType.Automated, 14, [Tag.Building, Tag.Power, Tag.Science], Expansion.Base, [new CardRequirement("power_tag", 2)], null, "Requires 2 Power tags. Increase your Energy production 3 steps"),
        D("133", "Symbiotic Fungus", CardType.Active, 4, [Tag.Microbe], Expansion.Base, [new CardRequirement("temperature", -14)], null, "Action: Add a microbe to ANOTHER card. Requires -14 C or warmer"),
        D("134", "Extreme-Cold Fungus", CardType.Active, 13, [Tag.Microbe], Expansion.Base, [new CardRequirement("max_temperature", -10)], null, "Action: Gain 1 plant or add 2 microbes to ANOTHER card. It must be -10 C or colder"),
        D("135", "Advanced Ecosystems", CardType.Automated, 11, [Tag.Animal, Tag.Microbe, Tag.Plant], Expansion.Base, [new CardRequirement("plant_tag", 1), new CardRequirement("microbe_tag", 1), new CardRequirement("animal_tag", 1)], new FixedVictoryPoints(3), "Requires a Plant tag, a Microbe tag, and an Animal tag"),
        D("136", "Great Dam", CardType.Automated, 12, [Tag.Building, Tag.Power], Expansion.Base, [new CardRequirement("oceans", 4)], new FixedVictoryPoints(1), "Requires 4 ocean tiles. Increase your Energy production 2 steps"),
        D("137", "Cartel", CardType.Automated, 8, [Tag.Earth], Expansion.CorporateEra, [], null, "Increase your MC production 1 step for each Earth tag you have, including this"),
        D("138", "Strip Mine", CardType.Automated, 25, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 2 steps. Increase your steel production 2 steps and your titanium production 1 step. Raise oxygen 2 steps"),
        D("139", "Wave Power", CardType.Automated, 8, [Tag.Power], Expansion.Base, [new CardRequirement("oceans", 3)], new FixedVictoryPoints(1), "Requires 3 ocean tiles. Increase your energy production 1 step"),
        D("140", "Lava Flows", CardType.Event, 18, [Tag.Event], Expansion.Base, [], null, "Raise temperature 2 steps and place this tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS"),
        D("141", "Power Plant", CardType.Automated, 4, [Tag.Building, Tag.Power], Expansion.Base, [], null, "Increase your Energy production 1 step"),
        D("142", "Mohole Area", CardType.Automated, 20, [Tag.Building], Expansion.Base, [], null, "Increase your heat production 4 steps. Place this tile ON AN AREA RESERVED FOR OCEAN"),
        D("143", "Large Convoy", CardType.Event, 36, [Tag.Event, Tag.Space, Tag.Earth], Expansion.Base, [], new FixedVictoryPoints(2), "Place an ocean tile and draw 2 cards. Gain 5 Plants or add 4 Animals to ANOTHER card"),
        D("144", "Titanium Mine", CardType.Automated, 7, [Tag.Building], Expansion.CorporateEra, [], null, "Increase your titanium production 1 step"),
        D("145", "Tectonic Stress Power", CardType.Automated, 18, [Tag.Building, Tag.Power], Expansion.Base, [new CardRequirement("science_tag", 2)], new FixedVictoryPoints(1), "Requires 2 Science tags. Increase your Energy production 3 steps"),
        D("146", "Nitrophilic Moss", CardType.Automated, 8, [Tag.Plant], Expansion.Base, [new CardRequirement("oceans", 3)], null, "Requires 3 ocean tiles and that you lose 2 plants. Increase your plant production 2 steps"),
        D("147", "Herbivores", CardType.Active, 12, [Tag.Animal], Expansion.Base, [new CardRequirement("oxygen", 8)], new PerResourceVictoryPoints(1, 2, "147"), "Effect: When you place a greenery tile, add an Animal to this card. Requires 8% oxygen. Add 1 Animal to this card. Decrease any Plant production 1 step. 1 VP per 2 Animals on this card"),
        D("148", "Insects", CardType.Automated, 9, [Tag.Microbe], Expansion.Base, [new CardRequirement("oxygen", 6)], null, "Requires 6% oxygen. Increase your Plant production 1 step for each plant tag you have"),
        D("149", "CEO's Favorite Project", CardType.Event, 1, [Tag.Event], Expansion.CorporateEra, [], null, ""),
        D("150", "Anti-gravity Technology", CardType.Active, 14, [Tag.Science], Expansion.CorporateEra, [new CardRequirement("science_tag", 7)], new FixedVictoryPoints(3), "Effect: When you play a card, you pay 2 MC less for it. Requires 7 science tags"),
        D("151", "Investment Loan", CardType.Event, 3, [Tag.Event, Tag.Earth], Expansion.CorporateEra, [], null, "Decrease your MC production 1 step. Gain 10 MC"),
        D("152", "Insulation", CardType.Automated, 2, [], Expansion.Base, [], null, "Decrease your heat production any number of steps and increase your MC production the same number of steps"),
        D("153", "Adaptation Technology", CardType.Active, 12, [Tag.Science], Expansion.Base, [], new FixedVictoryPoints(1), "Effect: Your global requirements are +2 or -2 steps, your choice in each case"),
        D("154", "Caretaker Contract", CardType.Active, 3, [], Expansion.CorporateEra, [new CardRequirement("temperature", 0)], null, "Action: Spend 8 heat to increase your terraform rating 1 step. Requires 0 C or warmer"),
        D("155", "Designed Microorganisms", CardType.Automated, 16, [Tag.Microbe, Tag.Science], Expansion.Base, [new CardRequirement("max_temperature", -14)], null, "It must be -14 C or colder. Increase your Plant production 2 steps"),
        D("156", "Standard Technology", CardType.Active, 6, [Tag.Science], Expansion.CorporateEra, [], null, "Effect: After you pay for a standard project, except selling patents, you gain 3 MC"),
        D("157", "Nitrite Reducing Bacteria", CardType.Active, 11, [Tag.Microbe], Expansion.Base, [], null, "Action: Add 1 Microbe to this card, or remove 3 Microbes to increase your TR 1 step. (Add 3 Microbes to this card"),
        D("158", "Industrial Microbes", CardType.Automated, 12, [Tag.Building, Tag.Microbe], Expansion.Base, [], null, "Increase your Energy production and your steel production 1 step each"),
        D("159", "Lichen", CardType.Automated, 7, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -24)], null, "Requires -24 C or warmer. Increase your Plant production 1 step"),
        D("160", "Power Supply Consortium", CardType.Automated, 5, [Tag.Power], Expansion.CorporateEra, [new CardRequirement("power_tag", 2)], null, "Requires 2 Power tags. Decrease any Energy production 1 step and increase your own 1 step"),
        D("161", "Convoy From Europa", CardType.Event, 15, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Place 1 ocean tile and draw 1 card"),
        D("162", "Imported GHG", CardType.Event, 7, [Tag.Event, Tag.Space, Tag.Earth], Expansion.Base, [], null, "Increase your heat production 1 step and gain 3 heat"),
        D("163", "Imported Nitrogen", CardType.Event, 23, [Tag.Event, Tag.Space, Tag.Earth], Expansion.Base, [], null, "Raise your TR 1 step and gain 4 Plants. Add 3 Microbes to ANOTHER card and 2 Animals to ANOTHER card"),
        D("164", "Micro-Mills", CardType.Automated, 3, [], Expansion.Base, [], null, "Increase your heat production 1 step"),
        D("165", "Magnetic Field Generators", CardType.Automated, 20, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 4 steps and increase your Plant production 2 steps. Raise your TR 3 steps"),
        D("166", "Shuttles", CardType.Active, 10, [Tag.Space], Expansion.Base, [new CardRequirement("oxygen", 5)], new FixedVictoryPoints(1), "Effect: When you play a Space card, you pay 2 MC less for it. Requires 5% oxygen. Decrease your Energy production 1 step and increase your MC production 2 steps"),
        D("167", "Import of Advanced GHG", CardType.Event, 9, [Tag.Event, Tag.Space, Tag.Earth], Expansion.Base, [], null, "Increase your heat production 2 steps"),
        D("168", "Windmills", CardType.Automated, 6, [Tag.Building, Tag.Power], Expansion.Base, [new CardRequirement("oxygen", 7)], new FixedVictoryPoints(1), "Requires 7% oxygen. Increase your Energy production 1 step"),
        D("169", "Tundra Farming", CardType.Automated, 16, [Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -6)], new FixedVictoryPoints(2), "Requires -6 C or warmer. Increase your Plant production 1 step and your MC production 2 steps. Gain 1 Plant"),
        D("170", "Aerobraked Ammonia Asteroid", CardType.Event, 26, [Tag.Event, Tag.Space], Expansion.Base, [], null, "Add 2 Microbes to ANOTHER card. Increase your heat production 3 steps and your Plant productions 1 step"),
        D("171", "Magnetic Field Dome", CardType.Automated, 5, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 2 steps and increase your Plant production 1 step. Raise your TR 1 step"),
        D("172", "Pets", CardType.Active, 10, [Tag.Animal, Tag.Earth], Expansion.Base, [], new PerResourceVictoryPoints(1, 2, "172"), "Effect: When any City tile is placed, add an Animal to this card. Add 1 Animal to this card. 1 VP per 2 Animals here"),
        D("173", "Protected Habitats", CardType.Active, 5, [], Expansion.CorporateEra, [], null, ""),
        D("174", "Protected Valley", CardType.Automated, 23, [Tag.Building, Tag.Plant], Expansion.Base, [], null, "Increase your MC production 2 steps. Place on a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step"),
        D("175", "Satellites", CardType.Automated, 10, [Tag.Space], Expansion.CorporateEra, [], null, "Increase your MC production 1 step for each space tag your have, including this one"),
        D("176", "Noctis Farming", CardType.Automated, 10, [Tag.Building, Tag.Plant], Expansion.Base, [new CardRequirement("temperature", -20)], new FixedVictoryPoints(1), "Requires -20 C or warmer. Increase your MC production 1 step and gain 2 Plants"),
        D("177", "Water Splitting Plant", CardType.Active, 12, [Tag.Building], Expansion.Base, [new CardRequirement("oceans", 2)], null, "Action: Spend 3 Energy to raise oxygen 1 step. Requires 2 ocean tiles"),
        D("178", "Heat Trappers", CardType.Automated, 6, [Tag.Building, Tag.Power], Expansion.Base, [], new FixedVictoryPoints(-1), "Decrease any heat production 2 steps and increase your Energy production 1 step"),
        D("179", "Soil Factory", CardType.Automated, 9, [Tag.Building], Expansion.Base, [], new FixedVictoryPoints(1), "Decrease your Energy production 1 step and increase your Plant production 1 step"),
        D("180", "Fuel Factory", CardType.Automated, 6, [Tag.Building], Expansion.CorporateEra, [], null, "Decrease your Energy production 1 step and increase your titanium and your MC production 1 step each"),
        D("181", "Ice Cap Melting", CardType.Event, 5, [Tag.Event], Expansion.Base, [new CardRequirement("temperature", 2)], null, "Requires +2 C or warmer. Place 1 ocean tile"),
        D("182", "Corporate Stronghold", CardType.Automated, 11, [Tag.Building, Tag.City], Expansion.CorporateEra, [], new FixedVictoryPoints(-2), "Decrease your Energy production 1 step and increase your MC production 3 steps. Place a City tile"),
        D("183", "Biomass Combustors", CardType.Automated, 4, [Tag.Building, Tag.Power], Expansion.Base, [new CardRequirement("oxygen", 6)], new FixedVictoryPoints(-1), "Requires 6% oxygen. Decrease any Plant production 1 step and increase your Energy production 2 steps"),
        D("184", "Livestock", CardType.Active, 13, [Tag.Animal], Expansion.Base, [new CardRequirement("oxygen", 9)], new PerResourceVictoryPoints(1, 1, "184"), "Action: Add 1 Animal to this card. (Requires 9% oxygen. Decrease your Plant production 1 step and increase your MC production 2 steps. 1 VP for each Animal on this card"),
        D("185", "Olympus Conference", CardType.Active, 10, [Tag.Building, Tag.Earth, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "When you play a Science tag, including this, either add a Science resource to this card, or remove a Science resource from this card to draw a card"),
        D("186", "Rad-Suits", CardType.Automated, 6, [], Expansion.CorporateEra, [new CardRequirement("cities", 2)], new FixedVictoryPoints(1), "Requires two cities in play. Increase your MC up 1 step"),
        D("187", "Aquifer Pumping", CardType.Active, 18, [Tag.Building], Expansion.Base, [], null, "Action: Spend 8 MC to place 1 ocean tile. STEEL MAY BE USED as if you were playing a Building card"),
        D("188", "Flooding", CardType.Event, 7, [Tag.Event], Expansion.Base, [], new FixedVictoryPoints(-1), "Place an ocean tile. IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 MC FROM THE OWNER OF ONE OF THOSE TILES"),
        D("189", "Energy Saving", CardType.Automated, 15, [Tag.Power], Expansion.Base, [], null, "Increase your Energy production 1 step for each City tile in play"),
        D("190", "Local Heat Trapping", CardType.Event, 1, [Tag.Event], Expansion.Base, [], null, "Spend 5 heat to gain either 4 Plants, or to add 2 Animals to ANOTHER card"),
        D("191", "Permafrost Extraction", CardType.Event, 8, [Tag.Event], Expansion.Base, [new CardRequirement("temperature", -8)], null, "Requires -8 C or warmer. Place 1 ocean tile"),
        D("192", "Invention Contest", CardType.Event, 2, [Tag.Event, Tag.Science], Expansion.CorporateEra, [], null, ""),
        D("193", "Plantation", CardType.Automated, 15, [Tag.Plant], Expansion.Base, [new CardRequirement("science_tag", 2)], null, "Requires 2 Science tags. Place a greenery tile and raise oxygen 1 step"),
        D("194", "Power Infrastructure", CardType.Active, 4, [Tag.Building, Tag.Power], Expansion.CorporateEra, [], null, "Action: Spend any amount of Energy and gain that amount of MC"),
        D("195", "Indentured Workers", CardType.Event, 0, [Tag.Event], Expansion.CorporateEra, [], new FixedVictoryPoints(-1), "The next card you play this generation costs 8 MC less"),
        D("196", "Lagrange Observatory", CardType.Automated, 9, [Tag.Space, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Draw 1 card"),
        D("197", "Terraforming Ganymede", CardType.Automated, 33, [Tag.Space, Tag.Jovian], Expansion.CorporateEra, [], new FixedVictoryPoints(2), "Raise your TR 1 step for each Jovian tag you have, including this"),
        D("198", "Immigration Shuttles", CardType.Automated, 31, [Tag.Space, Tag.Earth], Expansion.Base, [], new PerResourceVictoryPoints(1, 3, "198"), "Increase your MC production 5 steps. 1 VP for every 3rd City in play"),
        D("199", "Restricted Area", CardType.Active, 11, [Tag.Science], Expansion.CorporateEra, [], null, "Action: Spend 2 MC to draw a card. Place this tile"),
        D("200", "Immigrant City", CardType.Active, 13, [Tag.Building, Tag.City], Expansion.Base, [], null, "Effect: When a City tile is placed, including this, increase your MC production 1 step. Decrease your Energy production 1 step and decrease your MC production 2 steps. Place a City tile"),
        D("201", "Energy Tapping", CardType.Automated, 3, [Tag.Power], Expansion.CorporateEra, [], new FixedVictoryPoints(-1), "Decrease any Energy production 1 step and increase your own 1 step"),
        D("202", "Underground Detonations", CardType.Active, 6, [Tag.Building], Expansion.Base, [], null, "Action: Spend 10MC to increase your heat production 2 steps"),
        D("203", "Soletta", CardType.Automated, 35, [Tag.Space], Expansion.Base, [], null, "Increase your heat production 7 steps"),
        D("204", "Technology Demonstration", CardType.Event, 5, [Tag.Event, Tag.Space, Tag.Science], Expansion.CorporateEra, [], null, "Draw two cards"),
        D("205", "Rad-Chem Factory", CardType.Automated, 8, [Tag.Building], Expansion.Base, [], null, "Decrease your Energy production 1 step. Raise your TR 2 steps"),
        D("206", "Special Design", CardType.Event, 4, [Tag.Event, Tag.Science], Expansion.Base, [], null, "The next card you play this generation is +2 or -2 steps in global requirements, your choice"),
        D("207", "Medical Lab", CardType.Automated, 13, [Tag.Building, Tag.Science], Expansion.CorporateEra, [], new FixedVictoryPoints(1), "Increase your MC production 1 step for every 2 Building tags you have, including this"),
        D("208", "AI Central", CardType.Active, 21, [Tag.Building, Tag.Science], Expansion.CorporateEra, [new CardRequirement("science_tag", 3)], new FixedVictoryPoints(1), "Action: Draw 2 cards. Requires 3 Science tags to play. Decrease your Energy production 1 step"),
        D("P36", "House Printing", CardType.Automated, 10, [Tag.Building], Expansion.Prelude, [], new FixedVictoryPoints(1), "Increase your steel production 1 step"),
        D("P37", "Lava Tube Settlement", CardType.Automated, 15, [Tag.Building, Tag.City], Expansion.Prelude, [], null, "Decrease your energy production 1 step and increase your MC production 2 steps. Place a City Tile on a VOLCANIC AREA regardless of adjacent cities"),
        D("P38", "Martian Survey", CardType.Event, 9, [Tag.Event, Tag.Science], Expansion.Prelude, [new CardRequirement("max_oxygen", 4)], new FixedVictoryPoints(1), "Oxygen must be 4% or lower. Draw two cards"),
        D("P39", "PSYCHROPHILES", CardType.Active, 2, [Tag.Microbe], Expansion.Prelude, [new CardRequirement("max_temperature", -20)], null, "Action: Add 1 microbe to this card. Effect: When paying for a plant card, microbes here may be used as 2 MC each. Temperature must be -20 C or lower"),
        D("P40", "RESEARCH COORDINATION", CardType.Automated, 4, [Tag.Wild], Expansion.Prelude, [], null, ""),
        D("P41", "SF MEMORIAL", CardType.Automated, 7, [Tag.Building], Expansion.Prelude, [], new FixedVictoryPoints(1), "Draw 1 card"),
        D("P42", "Space Hotels", CardType.Automated, 12, [Tag.Space, Tag.Earth], Expansion.Prelude, [new CardRequirement("earth_tag", 2)], null, "Requires 2 Earth tags. Increase MC production 4 steps"),

        D("CORP01", "Credicor", CardType.Corporation, 0, [], Expansion.Base, [], null, "57"),
        D("CORP02", "Ecoline", CardType.Corporation, 0, [Tag.Plant], Expansion.Base, [], null, "You start with 2 plant production, 3 plants, and 36MC"),
        D("CORP03", "Helion", CardType.Corporation, 0, [Tag.Space], Expansion.Base, [], null, "You start with 3 heat production and 42 MC"),
        D("CORP04", "Mining Guild", CardType.Corporation, 0, [Tag.Building, Tag.Building], Expansion.Base, [], null, "Effect: Each time you get any steel or titanium as a placement bonus on the map, increase your steel production 1 step. You start with 30 MC, 5 steel, and 1 steel production"),
        D("CORP05", "Interplanetary Cinematics", CardType.Corporation, 0, [Tag.Building], Expansion.Base, [], null, "You start with 20 steel and 30 MC"),
        D("CORP06", "Inventrix", CardType.Corporation, 0, [Tag.Science], Expansion.Base, [], null, "45"),
        D("CORP07", "Phobolog", CardType.Corporation, 0, [Tag.Space], Expansion.Base, [], null, "You start with 10 titanium and 23 MC"),
        D("CORP08", "Tharsis Republic", CardType.Corporation, 0, [Tag.Building], Expansion.Base, [], null, "Effect: When any city tile is placed ON MARS, increase your MC production 1 step. When you place a city tile, gain 3 MC. 40"),
        D("CORP09", "Thorgate", CardType.Corporation, 0, [Tag.Power], Expansion.Base, [], null, "You start with 1 energy production and 48 MC"),
        D("CORP10", "United Nations Mars Initiative", CardType.Corporation, 0, [Tag.Earth], Expansion.Base, [], null, "40"),
        D("CORP11", "Teractor", CardType.Corporation, 0, [Tag.Earth], Expansion.CorporateEra, [], null, "60"),
        D("CORP12", "Saturn Systems", CardType.Corporation, 0, [Tag.Jovian], Expansion.CorporateEra, [], null, "Effect: Each time any Jovian tag is put into play, including this, increase your MC production 1 step. You start with 1 titanium production and 42 MC"),
        D("CORP18", "Cheung Shing Mars", CardType.Corporation, 0, [Tag.Building], Expansion.Prelude, [], null, "You start with 3 MC production and 44 MC"),
        D("CORP19", "Point Luna", CardType.Corporation, 0, [Tag.Space, Tag.Earth], Expansion.Prelude, [], null, "You start with 1 titanium production and 38 MC"),
        D("CORP20", "Robinson Industries", CardType.Corporation, 0, [], Expansion.Prelude, [], null, "Action: Spend 4 MC to increase (one of your LOWEST PRODUCTION 1 step.) You start with 47 MC"),
        D("CORP21", "Valley Trust", CardType.Corporation, 0, [Tag.Earth], Expansion.Prelude, [], null, "37 You start with 37 MC. As your first action, draw 3 Prelude cards, and play one of them. Discard the other two"),
        D("CORP22", "Vitor", CardType.Corporation, 0, [Tag.Earth], Expansion.Prelude, [], null, "45"),

        D("P01", "Allied Banks", CardType.Prelude, 0, [Tag.Earth], Expansion.Prelude, [], null, "Increase your MC production 4 steps. Gain 3 MC ."),
        D("P02", "Aquifer Turbines", CardType.Prelude, 0, [Tag.Power], Expansion.Prelude, [], null, "Place an Ocean. Increase your energy production 2 steps. Pay 3 MC ."),
        D("P03", "Biofuels", CardType.Prelude, 0, [Tag.Microbe], Expansion.Prelude, [], null, "Increase your energy and plant production 1 step. Gain 2 plants."),
        D("P04", "Biolab", CardType.Prelude, 0, [Tag.Science], Expansion.Prelude, [], null, "Increase your plant production 1 step. Draw 3 cards."),
        D("P05", "Biosphere Support", CardType.Prelude, 0, [Tag.Plant], Expansion.Prelude, [], null, "Increase your plant production 2 steps. Decrease your MC production 1 step."),
        D("P06", "Business Empire", CardType.Prelude, 0, [Tag.Earth], Expansion.Prelude, [], null, "Increase your MC production 6 steps. Pay 6 MC."),
        D("P07", "Dome Farming", CardType.Prelude, 0, [Tag.Building, Tag.Plant], Expansion.Prelude, [], null, "Increase your MC production 2 steps and plant production 1 step."),
        D("P08", "Donation", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Gain 21 MC."),
        D("P09", "Early Settlement", CardType.Prelude, 0, [Tag.Building, Tag.City], Expansion.Prelude, [], null, "Increase your plant production 1 step. Place a city tile."),
        D("P10", "Ecology Experts", CardType.Prelude, 0, [Tag.Microbe, Tag.Plant], Expansion.Prelude, [], null, "Increase your plant production 1 step. Play a card from hand, ignoring global requirements."),
        D("P11", "Eccentric Sponsor", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Play 1 card from hand with a 25 MC reduction."),
        D("P12", "Experimental Forest", CardType.Prelude, 0, [Tag.Plant], Expansion.Prelude, [], null, " Place 1 Greenery tile. Reveal cards until you reveal two cards with plant tags on them. Take them into your hand and discard the rest."),
        D("P13", "Galilean Mining", CardType.Prelude, 0, [Tag.Jovian], Expansion.Prelude, [], null, "Increase your titanium production 2 steps. Pay 5 MC."),
        D("P14", "Great Aquifer", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Place 2 Ocean tiles."),
        D("P15", "Huge Asteroid", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Increase Temperature 3 steps. Pay 5 MC."),
        D("P16", "Io Research Outpost", CardType.Prelude, 0, [Tag.Jovian, Tag.Science], Expansion.Prelude, [], null, "Increase your titanium production 1 step. Draw a card."),
        D("P17", "Loan", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Gain 30 MC. Decrease your MC production 2 steps."),
        D("P18", "Martian Industries", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Increase your energy and steel production 1 step. Gain 6 MC."),
        D("P19", "Metal-rich Asteroid", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Increase temperature 1 step. Gain 4 titanium and 4 steel."),
        D("P20", "Metals Company", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Increase your MC, steel and titanium production 1 step."),
        D("P21", "Mining Operations", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Increase your steel production 2 steps. Gain 4 steel."),
        D("P22", "Mohole", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Increase your heat production 3 steps. Gain 3 heat."),
        D("P23", "Mohole Excavation", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Increase your steel production 1 step and heat production 2 steps. Gain 2 heat."),
        D("P24", "Nitrogen Shipment", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Increase your plant production 1 step. Increase your TR 1 step. Gain 5 MC."),
        D("P25", "Orbital Construction Yard", CardType.Prelude, 0, [Tag.Space], Expansion.Prelude, [], null, "Increase your titanium production 1 step. Gain 4 titanium."),
        D("P26", "Polar Industries", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Increase your heat production 2 steps. Place an Ocean tile."),
        D("P27", "Power Generation", CardType.Prelude, 0, [Tag.Power], Expansion.Prelude, [], null, "Increase your energy production 3 steps."),
        D("P28", "Research Network", CardType.Prelude, 0, [Tag.Wild], Expansion.Prelude, [], null, "Increase your money production 1 step. Draw 3 cards."),
        D("P29", "Self-Sufficient Settlement", CardType.Prelude, 0, [Tag.Building, Tag.City], Expansion.Prelude, [], null, "Increase your money production 2 step. Place a City tile."),
        D("P30", "Smelting Plant", CardType.Prelude, 0, [Tag.Building], Expansion.Prelude, [], null, "Raise oxygen 2 steps. Gain 5 steel."),
        D("P31", "Society Support", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Increase your plant, energy and heat production 1 step. Decrease money production 1 step."),
        D("P32", "Supplier", CardType.Prelude, 0, [Tag.Power], Expansion.Prelude, [], null, "Increase your energy production 2 steps. Gain 4 steel."),
        D("P33", "Supply Drop", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Gain 3 titanium, 8 steel and 3 plants."),
        D("P34", "UNMI Contractor", CardType.Prelude, 0, [Tag.Earth], Expansion.Prelude, [], null, "Increase your TR 3 steps. Draw a card."),
        D("P35", "Acquired Space Agency", CardType.Prelude, 0, [], Expansion.Prelude, [], null, "Gain 6 titanium. Reveal cards until you reveal two cards with Space Tags. Take them into your hand, discard the rest."),
        };

        return cards.ToImmutableDictionary(c => c.Id);
    }

    private static CardDefinition D(
        string id, string name, CardType type, int cost,
        ImmutableArray<Tag> tags, Expansion expansion,
        ImmutableArray<CardRequirement> requirements,
        VictoryPoints? victoryPoints, string description) => new()
    {
        Id = id,
        Name = name,
        Type = type,
        Cost = cost,
        Tags = tags,
        Expansion = expansion,
        Requirements = requirements,
        VictoryPoints = victoryPoints,
        Description = description,
    };
}
